version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: databass-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: databass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - databass-net

  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: databass-mq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - databass-net

  minio:
    image: minio/minio
    container_name: databass-storage
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - databass-net

networks:
  databass-net:
    driver: bridge

volumes:
  postgres_data:
  minio_data: